os:
- linux
- osx
language: cpp
compiler:
- gcc
- clang
install: ./scripts/travis/install-deps.sh "${TRAVIS_OS_NAME}"
before_script:
- ./scripts/travis/clang-format-checker.sh
- ./scripts/travis/cppcheck_wrapper.sh ./src
script:
- mkdir build
- cd build
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then cmake .. -DCMAKE_PREFIX_PATH=/usr/local/opt/openssl ; else cmake ..; fi 
- make -j 2 && make test
- cd ..
branches:
  only:
  - master
  - develop
before_deploy: ./scripts/travis/build_tar.sh "${TRAVIS_OS_NAME}"
deploy:
  provider: s3
  access_key_id: AKIAIR7XPKSU5OIGJ5IA
  secret_access_key:
    secure: LCR1Bk98M/t7Rf6hKmXIPxjKmAXziqbggtdZZvI7p7gjwwDixU0ga0gbZRZbixAFkNuPFQZ/trKTpScwc9vChG4dGvd0AZsKaDncaYherdTY45OZMPjDCk4nfmanUxI9pTNw2FFKdiV/PCETsfc4ynoBQ0Blo6TSqti1NQWPZpM=
  bucket: monetas-builds
  skip_cleanup: true
  local-dir: s3
  upload-dir: ${TRAVIS_REPO_SLUG}/${TRAVIS_BRANCH}
  on:
    branch: ${TRAVIS_BRANCH}
